<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

<PropertyGroup>
	<GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
	<GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
	<GenerateAssemblyVersionAttribute>false</GenerateAssemblyVersionAttribute>
	<GenerateAssemblyFileVersionAttribute>false</GenerateAssemblyFileVersionAttribute>
	<GenerateAssemblyInformationalVersionAttribute>false</GenerateAssemblyInformationalVersionAttribute>
	<NuGetAuditMode>all</NuGetAuditMode>
	<SignAssembly>False</SignAssembly>
	<PublishAot>False</PublishAot>
	<PublishTrimmed>False</PublishTrimmed>
</PropertyGroup>

</Project>
